# Generated by Django 5.2.10 on 2026-01-15 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_App', '0002_alter_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='patient_profiles/')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('personal_phone', models.CharField(max_length=15)),
                ('emergency_phone', models.CharField(max_length=15)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('civil_status', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('bp', models.CharField(blank=True, max_length=10, null=True)),
                ('temp', models.CharField(blank=True, max_length=10, null=True)),
                ('pr', models.CharField(blank=True, max_length=10, null=True)),
                ('rr', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency_phone', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('complaints', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('section', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='PM_App.patient')),
            ],
        ),
    ]
