# Generated by Django 5.2.10 on 2026-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_App', '0003_patient_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
