# Generated by Django 5.2.10 on 2026-01-15 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_App', '0004_alter_patient_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaints',
            new_name='chief_complaint',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='remarks',
            new_name='final_diagnosis',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='bp',
            new_name='blood_pressure',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_phone',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='section',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='personal_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pr',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rr',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='temp',
        ),
        migrations.AddField(
            model_name='complaint',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='lab_examination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='test_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
