# Generated by Django 5.2.10 on 2026-01-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_App', '0005_rename_complaints_complaint_chief_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/img/default.png', null=True, upload_to='patient_profiles/'),
        ),
    ]
