# Generated by Django 5.2.10 on 2026-01-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_App', '0006_patient_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientComplaintArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('chief_complaint', models.TextField()),
                ('lab_examination', models.TextField(blank=True, null=True)),
                ('test_result', models.TextField(blank=True, null=True)),
                ('final_diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
