# Generated by Django 5.2.10 on 2026-01-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_App', '0007_patientcomplaintarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcomplaintarchive',
            name='is_arhived',
            field=models.BooleanField(default=True),
        ),
    ]
