# Generated by Django 5.2.10 on 2026-01-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_App', '0008_patientcomplaintarchive_is_arhived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcomplaintarchive',
            name='is_arhived',
        ),
        migrations.AddField(
            model_name='patientcomplaintarchive',
            name='complaint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='PM_App.complaint'),
        ),
    ]
