# Generated by Django 5.2.10 on 2026-01-16 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_App', '0009_remove_patientcomplaintarchive_is_arhived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcomplaintarchive',
            name='complaint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive', to='PM_App.complaint'),
        ),
    ]
